Repository CodeForPhilly/chime, pull requests merged in 2020-03, with the labels that each got.

#55 Refactor (move towards module)
  .github/workflows/pythonapp.yml
  Procfile
  app.py
  chime.code-workspace
  manual_tests.md
  penn_chime/__init__.py
  penn_chime/models.py
  penn_chime/presentation.py
  penn_chime/utils.py
  test_app.py
Labels: python

#170 Add cli
  cli.py
  penn_chime/models.py
  settings.cfg
Labels: python

#176 Move parameters
  src/app.py
  src/cli.py
  src/penn_chime/defaults.py
  src/penn_chime/models.py
  src/penn_chime/parameters.py
  src/penn_chime/presentation.py
  src/penn_chime/utils.py
  src/test_app.py
Labels: python

#190 Fix calculation of new infected cases
  src/penn_chime/charts.py
  src/penn_chime/models.py
  src/penn_chime/parameters.py
  src/penn_chime/presentation.py
  tests/test_app.py
Labels: bug

#192 Run black
  src/app.py
  src/cli.py
  src/penn_chime/charts.py
  src/penn_chime/defaults.py
  src/penn_chime/models.py
  src/penn_chime/parameters.py
  src/penn_chime/presentation.py
  src/penn_chime/settings.py
  src/penn_chime/utils.py
  tests/test_app.py
Labels: python, quickfix

#304 [dash] Bring number input step, min, and type to parity w/ Streamlit
  src/chime_dash/app/components/sidebar.py
Labels: dash

#309 [Dash] content and style update
  src/chime_dash/app/components/header.py
  src/chime_dash/app/components/intro.py
  src/chime_dash/app/components/menu.py
  src/chime_dash/app/components/navbar.py
  src/chime_dash/app/templates/en/header.yml
  src/chime_dash/app/templates/en/intro.md
Labels: dash

#311 [Dash] Fix for issue 247
  src/chime_dash/app/components/content.py
  src/chime_dash/app/components/definitions.py
  src/chime_dash/app/templates/en/footer.md
Labels: dash

#372 k8s deployments choke on repository URLs with uppercase letters
  .github/workflows/dockerpublish.yml
Labels: ci/cd

#373 Add timeout wait to Cypress
  .github/workflows/pythonapp.yml
Labels: bug, ci/cd
